[package]
name = "translator"
version = "0.1.0"
edition = "2024"

[dependencies]
docx-rust = "0.1.10"
futures = "0.3.31"
regex = "1.11.2"
rust-translate = "0.1.3"
tokio = { version = "1.0", features = ["full"] }

